from .problem1 import problem1
from .problem2 import problem2
from .problem3 import problem3
from .problem4 import problem4
from .problem5 import problem5
from .problem6 import problem6
from .problem7 import problem7
from .problem8 import problem8
from .problem9 import problem9
from .problem10 import problem10
from .problem11 import problem11
from .problem12 import problem12
from .problem13 import problem13
from .problem14 import problem14
from .problem15 import problem15
from .problem16 import problem16
from .problem17 import problem17
from .problem18 import problem18
from .problem19 import problem19
