"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from utils.number_theory import is_pentagonal_number, is_hexagonal_number
from utils.series import triangle_numbers


def problem45():
    generator = (
        triangle for triangle in triangle_numbers()
        if is_hexagonal_number(triangle) and is_pentagonal_number(triangle)
    )
    next(generator)
    next(generator)
    return next(generator)
